const root = document.querySelector('#root');
root.innerHTML = `
<main><div class="noise"></div>
<nav class="nav shell"><button class="brand" data-go="#top">IB<span>•</span></button><div class="navlinks"><button data-go="#work">Work</button><button data-go="#about">About</button><button data-go="#contact">Contact</button></div><button class="nav-cta" data-go="#contact">Let’s talk <span>→</span></button></nav>
<section id="top" class="hero shell"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> Available for collaborations</p><h1>Experiences<br>for the <em>web.</em></h1><p class="intro">Ibrahim is a frontend-focused Computer Systems Engineering student shaping clear, considered, and expressive digital experiences.</p><div class="hero-actions"><button class="primary" data-go="#work">Explore selected work <span>→</span></button><button class="text-btn" data-go="#about">More about me <span>↓</span></button></div></div><div class="portrait-stage"><div class="sun"></div><div class="ring ring-one"></div><div class="ring ring-two"></div><div class="portrait-card"><img src="Pictures/WhatsApp%20Image%202026-04-06%20at%205.16.12%20AM.jpeg" alt="Ibrahim, Frontend Developer"><div class="portrait-shine"></div></div><div class="orbit-tag tag-one">✦ &nbsp; UI / UX</div><div class="orbit-tag tag-two"><span class="code-mark">&lt;/&gt;</span> React</div><div class="vertical-text">SCROLL TO DISCOVER</div></div><div class="hero-foot"><p>BASED IN<br><strong>PESHAWAR, PK</strong></p><p>FOCUSING ON<br><strong>FRONTEND & WEB</strong></p><div class="scroll-cue"><span>01</span><i></i></div></div></section>
<section class="marquee"><div><span>Frontend developer</span><b>✦</b><span>Creative coding</span><b>✦</b><span>Digital experiences</span><b>✦</b><span>Frontend developer</span><b>✦</b><span>Creative coding</span><b>✦</b></div></section>
<section id="work" class="work shell"><div class="section-head"><p class="eyebrow">01 / Selected work</p><h2>Built to feel<br><em>memorable.</em></h2><p>Small details create the big picture. Here are a few projects where I put that belief into practice.</p></div><div class="projects">
<article class="project amazon"><div class="project-art"><div class="amazon-top">amazon<span>clone</span><i></i></div><div class="amazon-search"></div><div class="product-boxes"><b>Deals<br>made<br>visible</b><i></i><i></i></div><div class="art-no">01</div></div><div class="project-info"><div><p class="project-type">E-commerce interface</p><h3>Amazon Clone</h3></div><p class="project-caption">A responsive shopping experience with product flows, familiar patterns, and a clean product-first UI.</p><div class="tags"><span>React</span><span>CSS</span><span>Responsive</span><button>→</button></div></div></article>
<article class="project spotify"><div class="project-art"><div class="disc"><i></i></div><div class="music-name">MORNING<br><em>FREQUENCY</em></div><div class="equalizer">▂ ▅ ▃ ▇ ▂ ▆ ▄</div><div class="art-no">02</div></div><div class="project-info"><div><p class="project-type">Music streaming interface</p><h3>Spotify Clone</h3></div><p class="project-caption">A dark, immersive music interface designed around browseability, playback, and mood.</p><div class="tags"><span>HTML</span><span>CSS</span><span>JavaScript</span><button>→</button></div></div></article>
<article class="project portfolio"><div class="project-art"><div class="mini-orbit"><span>IB</span><i></i><b>✦</b><em>MAKE IT MOVE</em></div><div class="art-no">03</div></div><div class="project-info"><div><p class="project-type">Creative developer site</p><h3>Personal Portfolio</h3></div><p class="project-caption">An interactive portfolio concept that turns an introduction into an experience.</p><div class="tags"><span>React</span><span>Motion</span><span>UI Design</span><button>→</button></div></div></article>
</div></section>
<section id="about" class="about shell"><div class="about-index">02 <span> / ABOUT</span></div><div class="about-copy"><p class="big-copy">I’m a systems engineering student with a maker’s instinct and a soft spot for the <em>internet.</em></p><div class="about-bottom"><p>Currently studying Computer Systems Engineering at UET Peshawar, I’m growing into a frontend developer who cares deeply about the way a product looks, moves, and makes people feel.</p><a href="#contact">Let’s build something <span>→</span></a></div></div></section>
<section class="toolkit shell"><div class="section-head"><p class="eyebrow">03 / Toolkit</p><h2>Tools of the<br><em>trade.</em></h2></div><div class="skills"><div class="skill"><span>01</span><h3>HTML / CSS</h3><p>Semantic foundations & expressive styling</p><b>↗</b></div><div class="skill"><span>02</span><h3>JavaScript</h3><p>Interactive behavior & web logic</p><b>↗</b></div><div class="skill"><span>03</span><h3>React</h3><p>Component-driven user interfaces</p><b>↗</b></div><div class="skill"><span>04</span><h3>UI Design</h3><p>Intentional visual systems</p><b>↗</b></div></div></section>
<footer id="contact" class="footer"><div class="footer-glow"></div><div class="shell"><p class="eyebrow">04 / Contact</p><h2>Have an idea?<br><em>Let’s make it real.</em></h2><a class="email" id="email-link" href="mailto:YOUR_EMAIL_HERE">YOUR_EMAIL_HERE <span>→</span></a><div class="footer-bottom"><span>© 2026 IBRAHIM</span><span>UET PESHAWAR / PK</span><div><a id="linkedin-link" href="#">LINKEDIN</a><a id="github-link" href="#">GITHUB</a></div></div></div></footer></main>`;
document.querySelectorAll('[data-go]').forEach(button => button.addEventListener('click', () => document.querySelector(button.dataset.go).scrollIntoView({behavior:'smooth'})));
window.addEventListener('pointermove', e => { document.documentElement.style.setProperty('--mx', (e.clientX / innerWidth - .5) * 2); document.documentElement.style.setProperty('--my', (e.clientY / innerHeight - .5) * 2); });
